# Name(s)
**PUT YOUR FULL NAME(S) HERE**

**Instructions:** This is an individual assignment, but you may discuss your code with your neighbors.

# Python and NumPy

While other IDEs exist for Python development and for data science related activities, one of the most popular environments is Jupyter Notebooks.

This lab is not intended to teach you everything you will use in this course. Instead, it is designed to give you exposure to some critical components from NumPy that we will rely upon routinely.

## Exercise 0
Please read and reference the following as your progress through this course. 

* [What is the Jupyter Notebook?](https://nbviewer.jupyter.org/github/jupyter/notebook/blob/master/docs/source/examples/Notebook/What%20is%20the%20Jupyter%20Notebook.ipynb#)
* [Notebook Tutorial](https://www.datacamp.com/community/tutorials/tutorial-jupyter-notebook)
* [Notebook Basics](https://nbviewer.jupyter.org/github/jupyter/notebook/blob/master/docs/source/examples/Notebook/Notebook%20Basics.ipynb)

**In the space provided below, what are three things that still remain unclear or need further explanation?**

Nothing is unclear or needs further explanation.

## Exercises 1-7
For the following exercises please read the Python appendix in the Marsland textbook and answer problems A.1-A.7 in the space provided below.

## Exercise 1

In [1]:
import numpy as np

In [2]:
a = np.full((6,4), fill_value=2)

## Exercise 2

In [3]:
b = np.eye(N=6,M=4)*2 + np.full((6, 4), fill_value=1)

## Exercise 3

In [4]:
# Element-wise multiplication works
c = a * b

# Dot product cannot be run because the shapes do not work
# d = np.dot(a, b)

Element-wise multiplication of numpy arrays using * works because the two arrays have the same shape. The arrays cannot be matrix multiplied using dot() because the number of rows in **a** does not match the number of columns in **b**.

## Exercise 4

In [5]:
np.dot(a.transpose(), b)

np.dot(a, b.transpose())

array([[12., 12., 12., 12.,  8.,  8.],
       [12., 12., 12., 12.,  8.,  8.],
       [12., 12., 12., 12.,  8.,  8.],
       [12., 12., 12., 12.,  8.,  8.],
       [12., 12., 12., 12.,  8.,  8.],
       [12., 12., 12., 12.,  8.,  8.]])

The result of np.dot(**a**, **b**) will have **a**'s number of rows and **b**'s number of columns.

## Exercise 5

In [6]:
def print_stuff():
    print("Stuff")

print_stuff()

Stuff


## Exercise 6

In [8]:
def summarize_random_arrays():
    a = np.random.rand(3, 4)
    b = np.random.rand(3, 4)
    print("a:", a)
    print("b:", b)
    print("a+b:", a+b)
    print("mean of a:", np.mean(a))
    print("mean of b:", np.mean(b))

summarize_random_arrays()

a: [[0.0046508  0.22292971 0.68795008 0.58320462]
 [0.49154966 0.59601387 0.09145386 0.00798409]
 [0.86476083 0.35085853 0.63606696 0.62626382]]
b: [[0.9809406  0.84465573 0.90784862 0.68429433]
 [0.08663172 0.23909099 0.56764977 0.82214812]
 [0.11767358 0.07067784 0.78376796 0.12676274]]
a+b: [[0.9855914  1.06758544 1.5957987  1.26749895]
 [0.57818137 0.83510486 0.65910362 0.83013221]
 [0.9824344  0.42153637 1.41983492 0.75302656]]
mean of a: 0.43030723364795304
mean of b: 0.5193451666282495


## Exercise 7

In [23]:
def num_ones(arr):
    count = 0
    for v in arr.flatten():
        if v == 1.0:
            count += 1
    return count

print(num_ones(np.full((2, 3), fill_value=1.0)))
print(num_ones(np.eye(N=6,M=4)))

print(np.sum(np.where(np.full((2, 3), fill_value=1.0) == 1.0, 1, 0)))
print(np.sum(np.where(np.eye(N=6,M=4) == 1.0, 1, 0)))

6
4
6
4


## Excercises 8-???
While the Marsland book avoids using another popular package called Pandas, we will use it at times throughout this course. Please read and study [10 minutes to Pandas](https://pandas.pydata.org/pandas-docs/stable/getting_started/10min.html) before proceeding to any of the exercises below.

## Exercise 8
Repeat exercise A.1 from Marsland, but create a Pandas DataFrame instead of a NumPy array.

In [24]:
import pandas as pd

In [29]:
a = pd.DataFrame(np.full((6, 4), fill_value=2.0))
a

0    1    2    3
0  2.0  2.0  2.0  2.0
1  2.0  2.0  2.0  2.0
2  2.0  2.0  2.0  2.0
3  2.0  2.0  2.0  2.0
4  2.0  2.0  2.0  2.0
5  2.0  2.0  2.0  2.0

## Exercise 9
Repeat exercise A.2 using a DataFrame instead.

In [30]:
b = pd.DataFrame(np.eye(N=6,M=4)*2 + np.full((6, 4), fill_value=1))
b

0    1    2    3
0  3.0  1.0  1.0  1.0
1  1.0  3.0  1.0  1.0
2  1.0  1.0  3.0  1.0
3  1.0  1.0  1.0  3.0
4  1.0  1.0  1.0  1.0
5  1.0  1.0  1.0  1.0

## Exercise 10
Repeat exercise A.3 using DataFrames instead.

In [32]:
a * b

# matrix multiplication will still fail due to shape disagreement
# I'm also unsure how to perform matrix multiplication on
# dataframes without first converting to ndarrays...

0    1    2    3
0  6.0  2.0  2.0  2.0
1  2.0  6.0  2.0  2.0
2  2.0  2.0  6.0  2.0
3  2.0  2.0  2.0  6.0
4  2.0  2.0  2.0  2.0
5  2.0  2.0  2.0  2.0

## Exercise 11
Repeat exercise A.7 using a dataframe.

In [39]:
def count_ones(df):
    return df[df == 1.0].sum().sum()

count_ones(b)

20.0

## Exercises 12-14
Now let's look at a real dataset, and talk about ``.loc``. For this exercise, we will use the popular Titanic dataset from Kaggle. Here is some sample code to read it into a dataframe.

In [40]:
titanic_df = pd.read_csv(
    "https://raw.githubusercontent.com/dlsun/data-science-book/master/data/titanic.csv"
)
titanic_df

pclass  survived                                             name  \
0          1         1                    Allen, Miss. Elisabeth Walton   
1          1         1                   Allison, Master. Hudson Trevor   
2          1         0                     Allison, Miss. Helen Loraine   
3          1         0             Allison, Mr. Hudson Joshua Creighton   
4          1         0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)   
...      ...       ...                                              ...   
1304       3         0                             Zabour, Miss. Hileni   
1305       3         0                            Zabour, Miss. Thamine   
1306       3         0                        Zakarian, Mr. Mapriededer   
1307       3         0                              Zakarian, Mr. Ortin   
1308       3         0                               Zimmerman, Mr. Leo   

         sex      age  sibsp  parch  ticket      fare    cabin embarked boat  \
0     female  29.0000      0      0   24160  211.3375       B5        S    2   
1       male   0.9167      1      2  113781  151.5500  C22 C26        S   11   
2     female   2.0000      1      2  113781  151.5500  C22 C26        S  NaN   
3       male  30.0000      1      2  113781  151.5500  C22 C26        S  NaN   
4     female  25.0000      1      2  113781  151.5500  C22 C26        S  NaN   
...      ...      ...    ...    ...     ...       ...      ...      ...  ...   
1304  female  14.5000      1      0    2665   14.4542      NaN        C  NaN   
1305  female      NaN      1      0    2665   14.4542      NaN        C  NaN   
1306    male  26.5000      0      0    2656    7.2250      NaN        C  NaN   
1307    male  27.0000      0      0    2670    7.2250      NaN        C  NaN   
1308    male  29.0000      0      0  315082    7.8750      NaN        S  NaN   

       body                        home.dest  
0       NaN                     St Louis, MO  
1       NaN  Montreal, PQ / Chesterville, ON  
2       NaN  Montreal, PQ / Chesterville, ON  
3     135.0  Montreal, PQ / Chesterville, ON  
4       NaN  Montreal, PQ / Chesterville, ON  
...     ...                              ...  
1304  328.0                              NaN  
1305    NaN                              NaN  
1306  304.0                              NaN  
1307    NaN                              NaN  
1308    NaN                              NaN  

[1309 rows x 14 columns]

Notice how we have nice headers and mixed datatypes? That is one of the reasons we might use Pandas. Please refresh your memory by looking at the 10 minutes to Pandas again, but then answer the following.

## Exercise 12
How do you select the ``name`` column without using .iloc?

In [41]:
titanic_df['name']

0                         Allen, Miss. Elisabeth Walton
1                        Allison, Master. Hudson Trevor
2                          Allison, Miss. Helen Loraine
3                  Allison, Mr. Hudson Joshua Creighton
4       Allison, Mrs. Hudson J C (Bessie Waldo Daniels)
                             ...                       
1304                               Zabour, Miss. Hileni
1305                              Zabour, Miss. Thamine
1306                          Zakarian, Mr. Mapriededer
1307                                Zakarian, Mr. Ortin
1308                                 Zimmerman, Mr. Leo
Name: name, Length: 1309, dtype: object

## Exercise 13
After setting the index to ``sex``, how do you select all passengers that are ``female``? And how many female passengers are there?

In [42]:
## YOUR SOLUTION HERE
titanic_df.set_index('sex',inplace=True)
titanic_df.loc['female']

pclass  survived                                             name  \
sex                                                                         
female       1         1                    Allen, Miss. Elisabeth Walton   
female       1         0                     Allison, Miss. Helen Loraine   
female       1         0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)   
female       1         1                Andrews, Miss. Kornelia Theodosia   
female       1         1    Appleton, Mrs. Edward Dale (Charlotte Lamson)   
...        ...       ...                                              ...   
female       3         1  Whabee, Mrs. George Joseph (Shawneene Abi-Saab)   
female       3         1                 Wilkes, Mrs. James (Ellen Needs)   
female       3         1          Yasbeck, Mrs. Antoni (Selini Alexander)   
female       3         0                             Zabour, Miss. Hileni   
female       3         0                            Zabour, Miss. Thamine   

         age  sibsp  parch  ticket      fare    cabin embarked boat   body  \
sex                                                                          
female  29.0      0      0   24160  211.3375       B5        S    2    NaN   
female   2.0      1      2  113781  151.5500  C22 C26        S  NaN    NaN   
female  25.0      1      2  113781  151.5500  C22 C26        S  NaN    NaN   
female  63.0      1      0   13502   77.9583       D7        S   10    NaN   
female  53.0      2      0   11769   51.4792     C101        S    D    NaN   
...      ...    ...    ...     ...       ...      ...      ...  ...    ...   
female  38.0      0      0    2688    7.2292      NaN        C    C    NaN   
female  47.0      1      0  363272    7.0000      NaN        S  NaN    NaN   
female  15.0      1      0    2659   14.4542      NaN        C  NaN    NaN   
female  14.5      1      0    2665   14.4542      NaN        C  NaN  328.0   
female   NaN      1      0    2665   14.4542      NaN        C  NaN    NaN   

                              home.dest  
sex                                      
female                     St Louis, MO  
female  Montreal, PQ / Chesterville, ON  
female  Montreal, PQ / Chesterville, ON  
female                       Hudson, NY  
female              Bayside, Queens, NY  
...                                 ...  
female                              NaN  
female                              NaN  
female                              NaN  
female                              NaN  
female                              NaN  

[466 rows x 13 columns]

## Exercise 14
How do you reset the index?

In [46]:
# If you use .reset_index(inplace=True) then the dataframe will
# create a new unnamed index instead of using the "index" column

titanic_df.set_index('index', inplace=True)
titanic_df

sex  pclass  survived  \
index                             
0      female       1         1   
1        male       1         1   
2      female       1         0   
3        male       1         0   
4      female       1         0   
...       ...     ...       ...   
1304   female       3         0   
1305   female       3         0   
1306     male       3         0   
1307     male       3         0   
1308     male       3         0   

                                                  name      age  sibsp  parch  \
index                                                                           
0                        Allen, Miss. Elisabeth Walton  29.0000      0      0   
1                       Allison, Master. Hudson Trevor   0.9167      1      2   
2                         Allison, Miss. Helen Loraine   2.0000      1      2   
3                 Allison, Mr. Hudson Joshua Creighton  30.0000      1      2   
4      Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  25.0000      1      2   
...                                                ...      ...    ...    ...   
1304                              Zabour, Miss. Hileni  14.5000      1      0   
1305                             Zabour, Miss. Thamine      NaN      1      0   
1306                         Zakarian, Mr. Mapriededer  26.5000      0      0   
1307                               Zakarian, Mr. Ortin  27.0000      0      0   
1308                                Zimmerman, Mr. Leo  29.0000      0      0   

       ticket      fare    cabin embarked boat   body  \
index                                                   
0       24160  211.3375       B5        S    2    NaN   
1      113781  151.5500  C22 C26        S   11    NaN   
2      113781  151.5500  C22 C26        S  NaN    NaN   
3      113781  151.5500  C22 C26        S  NaN  135.0   
4      113781  151.5500  C22 C26        S  NaN    NaN   
...       ...       ...      ...      ...  ...    ...   
1304     2665   14.4542      NaN        C  NaN  328.0   
1305     2665   14.4542      NaN        C  NaN    NaN   
1306     2656    7.2250      NaN        C  NaN  304.0   
1307     2670    7.2250      NaN        C  NaN    NaN   
1308   315082    7.8750      NaN        S  NaN    NaN   

                             home.dest  
index                                   
0                         St Louis, MO  
1      Montreal, PQ / Chesterville, ON  
2      Montreal, PQ / Chesterville, ON  
3      Montreal, PQ / Chesterville, ON  
4      Montreal, PQ / Chesterville, ON  
...                                ...  
1304                               NaN  
1305                               NaN  
1306                               NaN  
1307                               NaN  
1308                               NaN  

[1309 rows x 14 columns]